- name: “Azure 上的 Ansible”文档
  href: ./index.yml
- name: 概述
  items:
    - name: 关于 Azure 上的 Ansible
      href: ./ansible-overview.md
- name: 快速入门
  expanded: true
  items:
    - name: 将 Ansible 解决方案模板部署到 CentOS
      href: ./ansible-deploy-solution-template.md
    - name: 在 Linux 虚拟机上安装 Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: 在 Cloud Shell 中运行 Playbook
      href: ./ansible-run-playbook-in-cloudshell.md
    - name: 使用 Linux 虚拟机
      expanded: true
      items:
        - name: 配置 Linux 虚拟机
          href: /azure/virtual-machines/linux/ansible-create-vm
          maintainContext: true
        - name: 管理 Linux 虚拟机
          href: /azure/virtual-machines/linux/ansible-manage-linux-vm
          maintainContext: true
- name: 教程
  items:
    - name: Azure 应用程序网关
      items:
        - name: 管理 Web 流量
          href: ./ansible-create-configure-application-gateway.md
    - name: Azure 应用服务
      items:
        - name: 配置应用
          href: ./ansible-create-configure-azure-web-apps.md
        - name: 缩放应用
          href: ./ansible-scale-azure-web-apps.md
    - name: Azure 开发测试实验室
      items:
        - name: 配置实验室
          href: ./ansible-devtest-labs-configure.md
    - name: Azure Kubernetes 服务 (AKS)
      items:
        - name: 配置 AKS 群集
          href: ./ansible-create-configure-aks.md
        - name: 配置 Azure CNI 网络
          href: ./ansible-aks-configure-cni-networking.md
        - name: 配置 kubenet 网络
          href: ./ansible-aks-configure-kubenet-networking.md
        - name: 在 AKS 群集中配置 RBAC 角色
          href: ./ansible-aks-configure-rbac.md
    - name: Azure HDInsight
      items:
        - name: 配置群集
          href: ./ansible-azure-hdinsight-configure.md
    - name: Azure 服务总线
      items:
        - name: 配置队列
          href: ./ansible-service-bus-queue-configure.md
        - name: 配置主题
          href: ./ansible-service-bus-topic-configure.md
    - name: 数据库
      items:
        - name: 配置 Azure Database for MySQL
          href: ./ansible-create-configure-mysql.md
        - name: 配置 Azure Cosmos DB 帐户
          href: ./ansible-data-cosmos-configure.md
        - name: 配置 Azure Redis 缓存
          href: ./ansible-data-cache-for-redis-configure.md
    - name: 动态库存
      items:
        - name: 管理 Azure 资源
          href: ./ansible-manage-azure-dynamic-inventories.md
    - name: 虚拟机
      items:
        - name: 创建共享映像库
          href: ansible-vm-create-from-shared-generalized-image.md
    - name: 虚拟机规模集
      items:
        - name: 配置
          href: ./ansible-create-configure-vmss.md
        - name: 部署
          href: ./ansible-deploy-app-vmss.md
        - name: 自动缩放
          href: ./ansible-auto-scale-vmss.md
        - name: 更新自定义映像
          href: ./ansible-vmss-update-image.md
        - name: 创建共享映像库
          href: ansible-vm-create-from-shared-generalized-image.md
    - name: 虚拟网络
      items:
        - name: 配置对等互连
          href: ./ansible-vnet-peering-configure.md
        - name: 配置路由表
          href: ./ansible-create-configure-route-table.md
- name: 示例
  items:
    - name: 适用于 Azure 的 Ansible 实验室
      href: 'https://github.com/microsoft/ansiblelabs'
    - name: Ansible Azure playbook 示例
      href: 'https://github.com/Azure-Samples/ansible-playbooks'
- name: 引用
  items:
    - name: Playbook 角色
      items:
        - name: azure_module
          href: 'https://galaxy.ansible.com/Azure/azure_modules/'
        - name: azure_preview_module
          href: 'https://galaxy.ansible.com/Azure/azure_preview_modules'
    - name: 发行版和功能
      href: ./ansible-matrix.md
    - name: 适用于 Azure 的所有模块
      href: 'https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules#azure'
- name: 工具
  items:
    - name: 适用于 Ansible 的 Visual Studio Code 扩展
      href: 'https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible'