- name: “已启用 Azure Arc 的 Kubernetes”文档
  href: index.yml
- name: 概述
  items:
    - name: 关于已启用 Arc 的 Kubernetes
      href: overview.md
- name: 示例
  items:
    - name: Azure Policy 内置策略定义
      items:
        - name: 已启用 Arc 的 Kubernetes
          href: policy-samples.md
- name: 操作指南
  items:
    - name: 连接到 Azure Arc
      items:
        - name: 连接群集
          href: connect-cluster.md
        - name: 加入服务主体
          href: create-onboarding-service-principal.md
    - name: 管理
      items:
        - name: 使用 GitOps 部署配置
          href: use-gitops-connected-cluster.md
        - name: 使用 GitOps 部署 Helm 图表
          href: use-gitops-with-helm.md
        - name: 通过 Azure Policy 强制使用 GitOps
          href: use-azure-policy.md
        - name: 用适用于容器的 Azure Monitor 进行监视
          href: ../../azure-monitor/insights/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: 使用 Azure Policy 的许可控制策略
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: 部署 IoT 工作负载
          href: deploy-azure-iot-edge-workloads.md
    - name: 疑难解答
      href: Troubleshooting.md